name: binding_generator
description: Tool to generate Dart for Godot from the extensions_api.json file
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  path: ^1.8.3
  tuple: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
