name: godot_dart_build
description: build_runner interface for simplifying binding to Godot
repository: https://github.com/fuzzybinary/godot_dart
version: 0.9.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  analyzer: ^9.0.0
  meta: ^1.9.0
  path: ^1.8.3
  collection: ^1.7.1
  build: ^4.0.0
  build_config: ^1.2.0
  source_gen: ^4.1.1
  godot_dart: '>=0.11.0<1.0.0'
  code_builder: ^4.5.0
  dart_style: ^3.0.0
  glob: ^2.1.2
  logging: ^1.2.0
  pubspec_parse: ^1.2.3
  built_collection: ^5.1.1

dev_dependencies:
  lints: ^2.0.0