name: godot_dart_build
description: build_runner interface for simplifying binding to Godot
repository: https://github.com/fuzzybinary/godot_dart
version: 0.3.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  analyzer: ^5.13.0
  meta: ^1.9.0
  path: ^1.8.3
  collection: ^1.7.1
  build: ^2.0.0
  build_config: ^1.1.1
  source_gen: ^1.3.2
  godot_dart: ^0.4.0    
  code_builder: ^4.5.0
  dart_style: ^2.3.1
  glob: ^2.1.2
  logging: ^1.2.0
  pubspec_parse: ^1.2.3
  built_collection: ^5.1.1

dev_dependencies:
  lints: ^2.0.0